chore: test ci on branch

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -72,6 +72,132 @@ exclude_combinations:
     width: 320
 
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Commands ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
+commands:
+  assume-role-and-persist-workspace:
+    description: 'Assumes deployment role and persists credentials across jobs'
+    parameters:
+      aws-account:
+        type: string
+    steps:
+      - checkout
+      - aws_assume_role/assume_role:
+          account: <<parameters.aws-account>>
+          profile_name: default
+          role: 'LBH_Circle_CI_Deployment_Role'
+      - persist_to_workspace:
+          root: *workspace_root
+          paths:
+            - .aws
+
+  deploy-lambda:
+    description: 'Deploys lambda via Serverless'
+    parameters:
+      stage:
+        type: enum
+        enum: ['development', 'staging', 'production']
+      aws-central-parameter-account:
+        type: enum
+        enum:
+          [
+            'AWS_ACCOUNT_DEVELOPMENT',
+            'AWS_ACCOUNT_STAGING',
+            'AWS_ACCOUNT_PRODUCTION',
+          ]
+    steps:
+      - *attach_workspace
+      - checkout
+      - run:
+          name: Fetch SSM parameters from central account
+          command: |
+            CENTRAL_ACCOUNT=${<<parameters.aws-central-parameter-account>>}
+
+            export ACTIVITY_HISTORY_API=$(aws ssm get-parameter \
+              --name arn:aws:ssm:eu-west-2:${CENTRAL_ACCOUNT}:parameter/housing-<<parameters.stage>>/mtfh-housing-<<parameters.stage>>/mtfh-housing/activity-history-api-url \
+              --query Parameter.Value \
+              --output text)
+            export LOOKUP_API_URL=$(aws ssm get-parameter \
+              --name arn:aws:ssm:eu-west-2:${CENTRAL_ACCOUNT}:parameter/housing-<<parameters.stage>>/mtfh-housing-<<parameters.stage>>/mtfh-housing/lookup-api-url \
+              --query Parameter.Value \
+              --output text)
+            export APP_URL=$(aws ssm get-parameter \
+              --name arn:aws:ssm:eu-west-2:${CENTRAL_ACCOUNT}:parameter/housing-<<parameters.stage>>/housing-register-<<parameters.stage>>/housing-register/app-url \
+              --query Parameter.Value \
+              --output text)
+            export AUTHORISED_ADMIN_GROUP=$(aws ssm get-parameter \
+              --name arn:aws:ssm:eu-west-2:${CENTRAL_ACCOUNT}:parameter/housing-<<parameters.stage>>/housing-register-<<parameters.stage>>/housing-register/authorised-admin-group \
+              --query Parameter.Value \
+              --output text)
+            export AUTHORISED_MANAGER_GROUP=$(aws ssm get-parameter \
+              --name arn:aws:ssm:eu-west-2:${CENTRAL_ACCOUNT}:parameter/housing-<<parameters.stage>>/housing-register-<<parameters.stage>>/housing-register/authorised-manager-group \
+              --query Parameter.Value \
+              --output text)
+            export AUTHORISED_OFFICER_GROUP=$(aws ssm get-parameter \
+              --name arn:aws:ssm:eu-west-2:${CENTRAL_ACCOUNT}:parameter/housing-<<parameters.stage>>/housing-register-<<parameters.stage>>/housing-register/authorised-officer-group \
+              --query Parameter.Value \
+              --output text)
+            export AUTHORISED_READONLY_GROUP=$(aws ssm get-parameter \
+              --name arn:aws:ssm:eu-west-2:${CENTRAL_ACCOUNT}:parameter/housing-<<parameters.stage>>/housing-register-<<parameters.stage>>/housing-register/authorised-readonly-group \
+              --query Parameter.Value \
+              --output text)
+            export HOUSING_REGISTER_API=$(aws ssm get-parameter \
+              --name arn:aws:ssm:eu-west-2:${CENTRAL_ACCOUNT}:parameter/housing-<<parameters.stage>>/housing-register-<<parameters.stage>>/housing-register/api-url \
+              --query Parameter.Value \
+              --output text)
+            export NOTIFY_TEMPLATE_NEW_APPLICATION=$(aws ssm get-parameter \
+              --name arn:aws:ssm:eu-west-2:${CENTRAL_ACCOUNT}:parameter/housing-<<parameters.stage>>/housing-register-<<parameters.stage>>/housing-register/notify-template-new-application \
+              --query Parameter.Value \
+              --output text)
+            export NOTIFY_TEMPLATE_DISQUALIFY=$(aws ssm get-parameter \
+              --name arn:aws:ssm:eu-west-2:${CENTRAL_ACCOUNT}:parameter/housing-<<parameters.stage>>/housing-register-<<parameters.stage>>/housing-register/notify-template-disqualify \
+              --query Parameter.Value \
+              --output text)
+            export NOTIFY_TEMPLATE_MEDICAL_NEED=$(aws ssm get-parameter \
+              --name arn:aws:ssm:eu-west-2:${CENTRAL_ACCOUNT}:parameter/housing-<<parameters.stage>>/housing-register-<<parameters.stage>>/housing-register/notify-template-medical-need \
+              --query Parameter.Value \
+              --output text)
+            export NEXT_PUBLIC_EVIDENCE_STORE=$(aws ssm get-parameter \
+              --name arn:aws:ssm:eu-west-2:${CENTRAL_ACCOUNT}:parameter/housing-<<parameters.stage>>/housing-register-<<parameters.stage>>/housing-register/evidence-store-url \
+              --query Parameter.Value \
+              --output text)              
+            export NEXT_PUBLIC_GTM_ID=$(aws ssm get-parameter \
+              --name arn:aws:ssm:eu-west-2:${CENTRAL_ACCOUNT}:parameter/housing-<<parameters.stage>>/housing-register-<<parameters.stage>>/housing-register/gtm-id \
+              --query Parameter.Value \
+              --output text)              
+              
+            echo "export ACTIVITY_HISTORY_API=${ACTIVITY_HISTORY_API}" >> $BASH_ENV
+            echo "export LOOKUP_API_URL=${LOOKUP_API_URL}" >> $BASH_ENV
+            echo "export APP_URL=${APP_URL}" >> $BASH_ENV
+            echo "export AUTHORISED_ADMIN_GROUP=${AUTHORISED_ADMIN_GROUP}" >> $BASH_ENV
+            echo "export AUTHORISED_MANAGER_GROUP=${AUTHORISED_MANAGER_GROUP}" >> $BASH_ENV
+            echo "export AUTHORISED_OFFICER_GROUP=${AUTHORISED_OFFICER_GROUP}" >> $BASH_ENV
+            echo "export AUTHORISED_READONLY_GROUP=${AUTHORISED_READONLY_GROUP}" >> $BASH_ENV
+            echo "export HOUSING_REGISTER_API=${HOUSING_REGISTER_API}" >> $BASH_ENV
+            echo "export NOTIFY_TEMPLATE_NEW_APPLICATION=${NOTIFY_TEMPLATE_NEW_APPLICATION}" >> $BASH_ENV
+            echo "export NOTIFY_TEMPLATE_DISQUALIFY=${NOTIFY_TEMPLATE_DISQUALIFY}" >> $BASH_ENV
+            echo "export NOTIFY_TEMPLATE_MEDICAL_NEED=${NOTIFY_TEMPLATE_MEDICAL_NEED}" >> $BASH_ENV
+            echo "export NEXT_PUBLIC_EVIDENCE_STORE=${NEXT_PUBLIC_EVIDENCE_STORE}" >> $BASH_ENV
+            echo "export NEXT_PUBLIC_GTM_ID=${NEXT_PUBLIC_GTM_ID}" >> $BASH_ENV
+
+      - run:
+          name: Build and deploy lambda
+          command: |
+            set -e
+            npx --yes serverless@4 deploy \
+              --stage <<parameters.stage>> \
+              --param="appUrl=${APP_URL}" \
+              --param="activityHistoryApi=${ACTIVITY_HISTORY_API}" \
+              --param="lookupApiUrl=${LOOKUP_API_URL}" \
+              --param="authorisedAdminGroup=${AUTHORISED_ADMIN_GROUP}" \
+              --param="authorisedManagerGroup=${AUTHORISED_MANAGER_GROUP}" \
+              --param="authorisedOfficerGroup=${AUTHORISED_OFFICER_GROUP}" \
+              --param="authorisedReadonlyGroup=${AUTHORISED_READONLY_GROUP}" \
+              --param="housingRegisterApi=${HOUSING_REGISTER_API}" \
+              --param="notifyTemplateNewApplication=${NOTIFY_TEMPLATE_NEW_APPLICATION}" \
+              --param="notifyTemplateDisqualify=${NOTIFY_TEMPLATE_DISQUALIFY}" \
+              --param="notifyTemplateMedicalNeed=${NOTIFY_TEMPLATE_MEDICAL_NEED}" \
+              --param="evidenceStore=${NEXT_PUBLIC_EVIDENCE_STORE}" \
+              --param="gtmId=${NEXT_PUBLIC_GTM_ID}" \
+              --conceal
 
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Jobs ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
 jobs:
@@ -199,80 +325,114 @@ jobs:
       - store_artifacts:
           path: cypress/results
 
-  deploy-development:
-    executor: aws-cli/default
+  # deploy-development:
+  #   executor: aws-cli/default
+  #   steps:
+  #     - checkout
+  #     - attach_workspace:
+  #         at: *workspace_root
+  #     - aws_assume_role/assume_role:
+  #         account: $AWS_ACCOUNT_DEVELOPMENT
+  #         profile_name: default
+  #         role: 'LBH_Circle_CI_Deployment_Role'
+  #     - run:
+  #         name: deploy
+  #         command: |
+  #           # aws_assume_role/assume_role stores credentials in ~/.aws/credentials, however
+  #           # environment variables take precence. These are set to do the initial config, so
+  #           # the role isn't actually assumed. We need to remove the environment variables in
+  #           # order for the aws_assume_role/assume_role output to be picked up.
+  #           #
+  #           # I think the lbh-hackit orb setup here could be replaced with direct use of the aws-cli/setup and
+  #           # aws-cli/role_arn_setup, which would remove the need for this cleanup.
+  #           unset AWS_ACCESS_KEY_ID
+  #           unset AWS_SECRET_ACCESS_KEY
+
+  #           npx --yes serverless@^4 deploy --stage development
+
+  # deploy-staging:
+  #   executor: aws-cli/default
+  #   steps:
+  #     - checkout
+  #     - attach_workspace:
+  #         at: *workspace_root
+  #     - aws_assume_role/assume_role:
+  #         account: $AWS_ACCOUNT_STAGING
+  #         profile_name: default
+  #         role: 'LBH_Circle_CI_Deployment_Role'
+  #     - run:
+  #         name: deploy
+  #         command: |
+  #           # aws_assume_role/assume_role stores credentials in ~/.aws/credentials, however
+  #           # environment variables take precence. These are set to do the initial config, so
+  #           # the role isn't actually assumed. We need to remove the environment variables in
+  #           # order for the aws_assume_role/assume_role output to be picked up.
+  #           #
+  #           # I think the lbh-hackit orb setup here could be replaced with direct use of the aws-cli/setup and
+  #           # aws-cli/role_arn_setup, which would remove the need for this cleanup.
+  #           unset AWS_ACCESS_KEY_ID
+  #           unset AWS_SECRET_ACCESS_KEY
+
+  #           npx --yes serverless@^4 deploy --stage staging
+
+  # deploy-production:
+  #   executor: aws-cli/default
+  #   steps:
+  #     - checkout
+  #     - attach_workspace:
+  #         at: *workspace_root
+  #     - aws_assume_role/assume_role:
+  #         account: $AWS_ACCOUNT_PRODUCTION
+  #         profile_name: default
+  #         role: 'LBH_Circle_CI_Deployment_Role'
+  #     - run:
+  #         name: deploy
+  #         command: |
+  #           # aws_assume_role/assume_role stores credentials in ~/.aws/credentials, however
+  #           # environment variables take precence. These are set to do the initial config, so
+  #           # the role isn't actually assumed. We need to remove the environment variables in
+  #           # order for the aws_assume_role/assume_role output to be picked up.
+  #           #
+  #           # I think the lbh-hackit orb setup here could be replaced with direct use of the aws-cli/setup and
+  #           # aws-cli/role_arn_setup, which would remove the need for this cleanup.
+  #           unset AWS_ACCESS_KEY_ID
+  #           unset AWS_SECRET_ACCESS_KEY
+
+  #           npx --yes serverless@^4 deploy --stage production
+
+  assume-role-development:
+    executor: node-executor
     steps:
-      - checkout
-      - attach_workspace:
-          at: *workspace_root
-      - aws_assume_role/assume_role:
-          account: $AWS_ACCOUNT_DEVELOPMENT
-          profile_name: default
-          role: 'LBH_Circle_CI_Deployment_Role'
-      - run:
-          name: deploy
-          command: |
-            # aws_assume_role/assume_role stores credentials in ~/.aws/credentials, however
-            # environment variables take precence. These are set to do the initial config, so
-            # the role isn't actually assumed. We need to remove the environment variables in
-            # order for the aws_assume_role/assume_role output to be picked up.
-            #
-            # I think the lbh-hackit orb setup here could be replaced with direct use of the aws-cli/setup and
-            # aws-cli/role_arn_setup, which would remove the need for this cleanup.
-            unset AWS_ACCESS_KEY_ID
-            unset AWS_SECRET_ACCESS_KEY
-
-            npx --yes serverless@^4 deploy --stage development
-
-  deploy-staging:
-    executor: aws-cli/default
+      - assume-role-and-persist-workspace:
+          aws-account: $AWS_ACCOUNT_DEVELOPMENT
+  assume-role-staging:
+    executor: node-executor
     steps:
-      - checkout
-      - attach_workspace:
-          at: *workspace_root
-      - aws_assume_role/assume_role:
-          account: $AWS_ACCOUNT_STAGING
-          profile_name: default
-          role: 'LBH_Circle_CI_Deployment_Role'
-      - run:
-          name: deploy
-          command: |
-            # aws_assume_role/assume_role stores credentials in ~/.aws/credentials, however
-            # environment variables take precence. These are set to do the initial config, so
-            # the role isn't actually assumed. We need to remove the environment variables in
-            # order for the aws_assume_role/assume_role output to be picked up.
-            #
-            # I think the lbh-hackit orb setup here could be replaced with direct use of the aws-cli/setup and
-            # aws-cli/role_arn_setup, which would remove the need for this cleanup.
-            unset AWS_ACCESS_KEY_ID
-            unset AWS_SECRET_ACCESS_KEY
-
-            npx --yes serverless@^4 deploy --stage staging
-
-  deploy-production:
-    executor: aws-cli/default
+      - assume-role-and-persist-workspace:
+          aws-account: $AWS_ACCOUNT_STAGING
+  assume-role-production:
+    executor: node-executor
     steps:
-      - checkout
-      - attach_workspace:
-          at: *workspace_root
-      - aws_assume_role/assume_role:
-          account: $AWS_ACCOUNT_PRODUCTION
-          profile_name: default
-          role: 'LBH_Circle_CI_Deployment_Role'
-      - run:
-          name: deploy
-          command: |
-            # aws_assume_role/assume_role stores credentials in ~/.aws/credentials, however
-            # environment variables take precence. These are set to do the initial config, so
-            # the role isn't actually assumed. We need to remove the environment variables in
-            # order for the aws_assume_role/assume_role output to be picked up.
-            #
-            # I think the lbh-hackit orb setup here could be replaced with direct use of the aws-cli/setup and
-            # aws-cli/role_arn_setup, which would remove the need for this cleanup.
-            unset AWS_ACCESS_KEY_ID
-            unset AWS_SECRET_ACCESS_KEY
-
-            npx --yes serverless@^4 deploy --stage production
+      - assume-role-and-persist-workspace:
+          aws-account: $AWS_ACCOUNT_PRODUCTION
+  deploy-to-development:
+    executor: node-executor
+    steps:
+      - deploy-lambda:
+          stage: 'development'
+          aws-central-parameter-account: 'AWS_ACCOUNT_DEVELOPMENT'
+  deploy-to-staging:
+    executor: node-executor
+    steps:
+      - deploy-lambda:
+          stage: 'staging'
+          aws-central-parameter-account: 'AWS_ACCOUNT_STAGING'
+  deploy-to-production:
+    executor: node-executor
+    steps:
+      - deploy-lambda:
+          stage: 'production'
+          aws-central-parameter-account: 'AWS_ACCOUNT_PRODUCTION'
 
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Workflows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
 workflows:
@@ -311,28 +471,48 @@ workflows:
             tags:
               only: /^hackney-housing-register-v[0-9]+(\.[0-9]+)*$/
 
-      - deploy-development:
+      - assume-role-development:
+          context: api-assume-role-development-context
+          # requires:
+          #   - run-tests
+          #   - run-cypress-e2e
+          filters:
+            tags:
+              ignore: /^hackney-housing-register-v[0-9]+(\.[0-9]+)*$/
+            branches:
+              # only: development
+              only: feature/upgrade-next
+
+      - deploy-to-development:
           context:
-            - api-assume-role-housing-development-context
             - housing-register-fe-build-context
             - Serverless Framework
+          requires:
+            - assume-role-development
+          filters:
+            tags:
+              ignore: /^hackney-housing-register-v[0-9]+(\.[0-9]+)*$/
+            branches:
+              only: feature/upgrade-next
+
+      - assume-role-staging:
+          context: api-assume-role-staging-context
           requires:
             - run-tests
             - run-cypress-e2e
           filters:
             tags:
-              ignore: /^hackney-housing-register-v[0-9]+(\.[0-9]+)*$/
+              only: /^hackney-housing-register-v[0-9]+(\.[0-9]+)*$/
             branches:
-              only: development
+              ignore: /.*/
 
-      - deploy-staging:
+      - deploy-to-staging:
           context:
             - api-assume-role-housing-staging-context
             - housing-register-fe-build-context
             - Serverless Framework
           requires:
-            - run-tests
-            - run-cypress-e2e
+            - assume-role-staging
           filters:
             tags:
               only: /^hackney-housing-register-v[0-9]+(\.[0-9]+)*$/
@@ -342,20 +522,30 @@ workflows:
       - permit-deploy-production:
           type: approval
           requires:
-            - deploy-staging
+            - deploy-to-staging
           filters:
             tags:
               only: /^hackney-housing-register-v[0-9]+(\.[0-9]+)*$/
             branches:
               ignore: /.*/
 
-      - deploy-production:
+      - assume-role-production:
+          context: api-assume-role-production-context
+          requires:
+            - permit-deploy-production
+          filters:
+            tags:
+              only: /^hackney-housing-register-v[0-9]+(\.[0-9]+)*$/
+            branches:
+              ignore: /.*/
+
+      - deploy-to-production:
           context:
             - api-assume-role-housing-production-context
             - housing-register-fe-build-context
             - Serverless Framework
           requires:
-            - permit-deploy-production
+            - assume-role-production
           filters:
             tags:
               only: /^hackney-housing-register-v[0-9]+(\.[0-9]+)*$/
